root = "." # The root directory of the project
tmp_dir = "tmp" # The directory to store temporary files

[build] # The build configuration
    bin = "main" # The name of the binary file to be generated after building the project
    cmd = "go build -o {{.Output}} {{.Input}}" # The command to build the project
    exclude = ["tmp/*", "client/*"] # Specify the files or directories to be excluded from the monitoring for changes
    include = ["**/*.go"] # Specify the files or directories to be included in the monitoring for changes
    ignore = ["tmp/*"] # Specify the files or directories to be ignored when triggering a build